### ISSUE TITLE
手机浏览

### ISSUE THREAD

**Issue by disburden** [xing5/hexo-theme-codeland#1]
为什么我用了你的皮肤后,在iphone手机safari浏览器中查看博客只会显示第一条记录?

**Comment by xing5** [comment]
我刚刚试了试用iphone 4S safari访问你的博客， 是可以看到所有文章的。

**Comment by disburden** [comment]
不好意思，好像是可以，应该是我这里网络太慢的原因，等很久才出来，关闭吧
